[package]
name = "ambient_fb_schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs2js = "0.2"
firebase-wasm = { git = "https://github.com/FredrikNoren/firebase-wasm-rs.git", rev = "3b871f6" }
ambient_project = { git = "https://github.com/AmbientRun/Ambient.git", rev = "8839542" }
sha2 = "0.10.6"
base64ct = { version = "1.6.0", features = ["alloc"] }
