// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Activity } from "./Activity";

export interface DbActivity { timestamp: Timestamp, user_id: string, content: Activity, }