// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DbCollections = "packages" | "profiles" | "api_keys" | "deployments" | "servers" | "server_logs" | "running_servers" | "sharded_servers" | "upvotes" | "activities";