// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbPackageContent } from "./DbPackageContent";

export interface DbPackage { owner_id: string, created: Timestamp, updated: Timestamp, deleted: boolean, latest_deployment: string, deployments: Array<string>, featured: number | null, latest_screenshot_url: string, latest_readme_url: string, total_upvotes: number, name: string, description: string, content: Array<DbPackageContent>, for_playables: Array<string>, public: boolean, }