// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DbPackageContent = "Playable" | "Example" | "NotExample" | "Asset" | "Models" | "Animations" | "Textures" | "Materials" | "Fonts" | "Code" | "Schema" | "Audio" | "Other" | "Tool" | "Mod";