// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DbCollections } from "./DbCollections";

export interface DbUpvote { collection: DbCollections, user_id: string, item_id: string, }